apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service-deployment
spec:
  selector:
    matchLabels:
      # This matches with the selector in authentication-service-s.yml at line no 14 , and template labels at line no 14 below
      app: authentication-service
  replicas: 1
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service-c
          image: authentication-service
          imagePullPolicy: IfNotPresent
---