---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service-c
          image: user-service
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-s
  labels:
    app: user-service
spec:
  type: NodePort
  ports:
   - port: 8080
     targetPort: 8080
     nodePort: 8080
  selector:
    app: user-service




