apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  labels:
    app: authentication-service
spec:
  selector:
    matchLabels:
      app: authentication-service
  replicas: 1
  template:
    metadata:
      name: authentication-service
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service-c
          image: authentication-service
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service-c
          image: user-service
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1
  template:
    metadata:
      name: order-service
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service-c
          image: order-service
          imagePullPolicy: IfNotPresent


---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service-s
  labels:
    app: authentication-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31001
  selector:
    app: authentication-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-s
  labels:
    app: user-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31002
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-s
  labels:
    app: order-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31003
  selector:
    app: order-service