apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
  labels:
    app: apigateway-service
spec:
  selector:
    matchLabels:
      app: apigateway-service
  replicas: 1
  template:
    metadata:
      name: apigateway-service
      labels:
        app: apigateway-service
    spec:
      containers:
        - name: apigateway-service-c
          image: apigateway
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service-s
  labels:
    app: apigateway-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31004
  selector:
    app: apigateway-service