apiVersion: v1
kind: Service
metadata:
  name: user-service-s
  labels:
    app: user-service-deployment
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31001
  selector:
    app: authentication-service