apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-search-service
  labels:
    app: elastic-search-service
spec:
  selector:
    matchLabels:
      app: elastic-search-service
  replicas: 1
  template:
    metadata:
      name: elastic-search-service
      labels:
        app: elastic-search-service
    spec:
      containers:
        - name: elastic-search-c
          image: authentication-service
          imagePullPolicy: IfNotPresent
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"


---