apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service-deployment
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service-c
          image: user-service
          imagePullPolicy: IfNotPresent
---